config/routes.rb
ContentPublishing::Application.routes.draw do
  devise_for :admins

  devise_for :users

  root :to => "home#index"

  scope "/admin" do
    resources :users
  end

  resources :articles
  put 'articles/:id/publish' => 'articles#publish', as: :publish_article

  match '*unmatched_route', :to => 'application#raise_not_found!'
end

app/models/article.rb
class Article < ActiveRecord::Base
  include ActiveModel::Validations
  include ::ArticleState

  SORT_BY_UPDATED_AT_DESC = 'updated_at desc'

  attr_accessible :name, :content
  attr_accessible :state

  validates :name, uniqueness: {case_sensitive: false}, presence: true
  validates :state, inclusion: { in: VALID_STATES } , presence: true
  validates :author, presence: true

  belongs_to :author, class_name: User.name
  belongs_to :publisher, class_name: User.name

  after_initialize :init

  scope :all_for_author, ->(author) { where(author_id: author).order(SORT_BY_UPDATED_AT_DESC) }
  scope :published_articles, -> { where(state: ArticleState::PUBLISHED) }

  def init
    self.state = DRAFT if self.new_record?
  end

  def self.editable_by user
    (user.is_editor? or user.is_admin?) ? Article.order(SORT_BY_UPDATED_AT_DESC) : Article.all_for_author(user)
  end

  def self.draft_articles_count_for author
    self.count_by_state author, ArticleState::DRAFT
  end

  def self.published_articles_count_for author
    self.count_by_state author, ArticleState::PUBLISHED
  end

  def can_update? user
    if user.is_admin? or user.is_editor? or self.author == user
      return true
    end

    false
  end

  private

  def self.count_by_state author, state
    if author.is_editor? or author.is_admin?
      Article.where({state:state}).count
    else
      Article.where(author_id: author).where({state:state}).count
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  skip_before_filter :authenticate_user!, only: [:show]
  before_filter :article_exists? , only: [:show, :edit, :update]
  before_filter :can_update? , only: [:edit, :update]


  authorize_resource

  def index
    @articles = Article.editable_by(current_user)
  end

  def new
  end

  def show
    @article = Article.where(id:params[:id], state: ArticleState::PUBLISHED).first
    if !@article
      render_error(404, I18n.t("articles.does_not_exist"))
      return
    end
  end

  def create
    @article = Article.new params[:article]
    @article.author = current_user

    if @article.save
      flash[:success] = I18n.t('articles.successfully_created')
      redirect_to articles_path
    else
      flash[:error] = I18n.t('articles.create_error')
      render action: :new
    end
  end

  def edit
    @article = @original_article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update_attributes(params[:article])
      flash[:success] = I18n.t('articles.successfully_updated')
      redirect_to articles_path
    else
      @original_article = Article.find(@article.id)
      flash[:error] = I18n.t('articles.update_error')
      render action: :edit
    end
  end

  def publish
    @article = Article.find(params[:id])

    if !current_user.can_publish?
      flash[:error] = I18n.t('articles.not_allowed_to_publish')
      edit
      render action: :edit
      return
    end

    @article.publish!(current_user)
    flash[:success] = I18n.t('articles.successfully_published')
    redirect_to articles_path
  end

  private

  def can_update?
    unless Article.find(params[:id]).can_update? current_user
      render_error(400, I18n.t("not_authorized"))
      return
    end
  end

  def article_exists?
    unless Article.exists?(params[:id])
      render_error(404, I18n.t("articles.does_not_exist"))
      return
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper

  def display_content_text content
    "#{content[0..100]} ...." if content
  end
end

app/views/articles/_form.html.slim
= form_for(:article, :url => url, :html => { :method => method }) do |f|
  .form-group
    = f.label :name
    = f.text_field :name, :autofocus => true ,  maxlength:'150' , class: 'text-width'

  .form-group
    = f.label :content
    = f.text_area :content, :rows => '15', class: 'text-area-width'

  .clear
  = submit_tag('Save Article', class: "btn btn-primary btn-default")

app/views/articles/_publish.html.slim
- if @article.published?
  .publisher
    small.small = "Published by: #{@article.publisher.email}"
- elsif current_user.can_publish?
  = form_tag(publish_article_path(@article.id), method: :put, class: 'pull-right')
    = submit_tag('Publish', class: "btn btn-success btn-default")

app/views/articles/edit.html.slim
.article-form

  = render partial: 'errors/validation_error', locals: {errors: @article.errors}

  h3
    em.article-name.text-primary #{@original_article.name}
    span.badge.article-state #{@original_article.state}
    = render partial: 'publish'
  hr
  = render partial: 'form', locals: { method: 'put', url: "#{article_path(@article.id)}"}

app/views/articles/index.html.erb
<h2> Articles </h2>
<hr>

<table class='table table-striped'>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>
  <% @articles.each do |art| %>
    <tr>
      <td> <%= art.id %></td>
      <td> <%= art.name %></td>
      <td> <%= art.state %></td>
      <td> <%= link_to( 'Edit', edit_article_path(id:art.id)) %> </td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
  <div class='article-form'>
<h3> Create New Article </h3>

  <hr>

  <%  if @article%> 
    <%= render partial: 'errors/validation_error', locals: {errors: @article.errors} %>
  <% end %>

<%= form_for(:article, :url => articles_path, :html => { :method => :post }) do |f| %>

  <div><%= f.label :name %><br />
  <%= f.text_field :name, :autofocus => true ,  maxlength:'150' , class: 'text-width' %></div>

  <div><%= f.label :content %><br />
    <%= f.text_area :content, :rows => '15', class: 'text-area-width' %></div>

  <button type="submit" class="btn btn-primary"> Save Article</button>

<% end %>

</div>

app/views/articles/show.html.slim
h2 = @article.name
hr
p
  = @article.content